### PR TITLE
Add buttons to filter by location

### PR DESCRIPTION
**Pull request by dillonfagan**

### CODE REVIEW

**Comment by dillonfagan** [comment]
Can we cut the 0.4 release with this change?

**Comment by cmilkaitis** [comment]
crispy

**Review by cmilkaitis — APPROVED** [review]
:)

**Comment by mdantuono** [comment]
One thing I would say is the location switching does not work properly when you are searching an item

**Comment by dillonfagan** [comment]
Good catch on the search bug @mdantuono.
I fixed it by consolidating searchResults with shownThings, which has the added benefit of still showing the categories when you search.

**Review by mdantuono — APPROVED** [review]

**Pull request merged**
