### PR TITLE
Update verbiage and add page for donations

### PR DESCRIPTION
**Pull request by dillonfagan**
Updates the verbiage on the homepage, adds a donations page, and a link to a Google form. Also changed "member-owned" to "non-profit" where applicable.

### CODE REVIEW

**Review by mdantuono — COMMENTED** [review]
Did we want to say anything more about us searching for space or anything relating to that part of the startup?

**Comment by dillonfagan** [comment]
@mdantuono I didn't and you're absolutely right. I can try finding a way to work that in as well.

**Comment by dillonfagan** [comment]
Added wording to explain that we're looking for a low-rent space and to contact Starboard. Also added a button to our new Gofundme campaign.

**Comment by dillonfagan** [comment]
@mdantuono too slow

**Pull request merged**
